steps:
  - label: 'hlint'
    command: 'scripts/ci/nix-shell.sh -p hlint moreutils --run scripts/haskell/lint.sh'
    agents:
      system: x86_64-darwin
      queue: lahlah

  - label: 'cardano-x86_64-darwin'
    command: 'scripts/ci/nix-shell.sh --run scripts/ci/ci.sh'
    agents:
      system: x86_64-darwin
      queue: lahlah
